version: "3.5"

services:
  postgres:
    container_name: postgres_ads
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./db:/data/postgres

volumes:
  db:
